### ISSUE TITLE
$combinations.finalprice is not available in $combinations

### ISSUE THREAD

**Issue by hakeryk2** [rubendivall/PrestaShop-SEO-Snippets#3]
Just a quicky - You used  "price": "{$combination.finalprice|round:'2'}", in Your code but there is no array value like this in $combinations array. Is it Your own modification?

**Comment by rubendivall** [comment]
Hi @hakeryk2 thank your for your aprecation. You are right, finalprice is a own override.

The code is now fixed and works fine with Product::getPriceStatic(id_product, tax, id_product_combination)

Try the new commit.

Does it work in your Prestashop version?

Best regards

**Comment by rubendivall** [comment]
Test and fixed
